# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-11-14 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainwheel',
            name='img',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mainwheel',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mainwheel',
            name='trackid',
            field=models.CharField(max_length=16),
        ),
    ]
